services:
    
    db:
        image: postgres:17
        container_name: otro
        restart: always
        environment:
            POSTGRES_USER: usuario
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        volumes:
            - /var/lib/postgresql/17/otro:/var/lib/postgresql/data
            - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
        ports:
            - 5434:5432
